export const PRIVACY_LAST_UPDATED = "January 31, 2023";

export const PRIVACY_DEFINITIONS = [
  {
    term: "Website",
    text: "EarlyPay site, which can be accessed via this website.",
  },
  {
    term: "User",
    text: "This refers to you.",
  },
  {
    term: "Country",
    text: "Nigeria.",
  },
  {
    term: "Cookie",
    text: "This is a small amount of data generated by a website and saved by your web browser.",
  },
  {
    term: "Service",
    text: "This refers to the services being provided.",
  },
] as const;
